Solaris.BlockExplorer.UI/Controllers/SearchController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Solaris.BlockExplorer.UI.Models.ViewModels;
using Solaris.BlockExplorer.UI.Services;

namespace Solaris.BlockExplorer.UI.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchModelService _searchModelService;

        public SearchController(ISearchModelService searchModelService)
        {
            _searchModelService = searchModelService;
        }

        public async Task<IActionResult> Index(string query)
        {
            var searchResults = await _searchModelService.Search(query);

            var types = new[]
            {
                "Block",
                "Transaction",
                "Address"
            };

            foreach (var type in types)
            {
                if (searchResults.Count(p => p.Type == type) == 1)
                    return RedirectToRoute(type, new
                    {
                        searchResults.Single(p => p.Type == type).Id
                    });
            }

            return View(new SearchViewModel
            {
                SearchResults = await _searchModelService.Search(query)
            });
        }
    }
}

Solaris.BlockExplorer.UI/Views/Shared/Navbar.cshtml
@using Solaris.BlockExplorer.UI.HtmlHelpers
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand ml-2 mr-2" href="~/">
        <div class="nav-brand-img"></div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#top-navbar" aria-controls="top-navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="top-navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item @Url.IsLinkActive("Index", "Home")">
                <a class="nav-link" href="@Url.Action("Index", "Home")"><i class="fas fa-home text-warning"></i> Blocks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "RichList")"><i class="fas fa-tachometer-alt text-warning"></i> Rich List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "ApiDocumentation")"><i class="fas fa-info-circle text-warning"></i> Api</a>
            </li>
        </ul>
        <div class="mr-2 my-2 my-md-0">
            <ul class="navbar-nav">
                <li class="nav-item navbar-right">
                    <div class="form-inline">
                        <form method="get" action="@Url.Action("Index", "Search")">
                            <div class="form-group ">
                                <div class="input-group" style="width: 320px;">
                                    <input type="text" class="form-control" aria-describedby="search-addon" placeholder="Search for address, block, transaction..." autocomplete="off" name="Query">
                                    <div class="input-group-append">
                                        <span class="input-group-text ml-2" id="search-addon"><i class="fa fa-search icons"></i></span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <div class="mr-4 my-2 my-md-0">
            <ul class="navbar-nav">
                <li class="nav-item navbar-right">
                    <table>
                        <tr>
                            <td><i class="fas fa-sun text-warning"></i></td>
                            <td>
                                <label class="switch mt-3">
                                    <input type="checkbox" data-bind="event: { change: setViewMode }, checked: viewModeChecked;" checked="checked">
                                    <span class="switch-slider round"></span>
                                </label>
                            </td>
                            <td><i class="fas fa-moon"></i></td>
                        </tr>
                    </table>
                </li>
            </ul>
        </div>
    </div>
</nav>

Solaris.BlockExplorer.UI/Views/Shared/_Layout.cshtml
@using Solaris.BlockExplorer.UI.HtmlHelpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/libs.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/highlightjs/styles/vs@(Html.ViewMode() == "night-mode" ? "2015" : "").min.css" asp-append-version="true" />

    <link rel="icon" href="~/favicon.png" type="image/png" asp-append-version="true">
    
    <script src="~/js/libs.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>

    <script>
        Endpoints.prototype.darkTheme = '@Url.Content("~/css/highlightjs/styles/vs2015.min.css")';
        Endpoints.prototype.lightTheme = '@Url.Content("~/css/highlightjs/styles/vs.min.css")';
        Endpoints.prototype.marketData = '@Url.Action("MarketData", "Home")';
        Endpoints.prototype.wealthChartData = '@Url.Action("GetWealthChartData", "RichList")';
        Endpoints.prototype.difficultyChartData = '@Url.Action("GetDifficultyData", "Statistics")';
        Endpoints.prototype.transactionCountChartData = '@Url.Action("GetTransactionCountData", "Statistics")';
        Endpoints.prototype.blockSizeChartData = '@Url.Action("GetBlockSizeData", "Statistics")';
        Endpoints.prototype.block = '@Url.Action("Block", "Home")';

        Settings.prototype.ticker = '@ViewBag.Ticker';
        Settings.prototype.viewMode = '@Html.ViewMode()';
    </script>
</head>
<body data-bind="css: viewMode" class="@Html.ViewMode()">
    <header>
        <partial name="Navbar" />
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 side-columns">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="d-flex justify-content-center position-absolute footer">
        <div class="container">
            <div class="row pt-2">
                <div class="col-sm-12 col-md-12 text-center">
                    @if (string.IsNullOrEmpty(@ViewBag.Website))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Website" class="text-white" target="_blank"><i class="fas fa-globe mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Twitter))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Twitter" class="text-white" target="_blank"><i class="fab fa-twitter mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Telegram))
                    {
                        <div class="d-none"></div>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Twitter))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Facebook" class="text-white" target="_blank"><i class="fab fa-facebook mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Telegram))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Telegram" class="text-white" target="_blank"><i class="fab fa-telegram-plane mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Discord))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Discord" class="text-white" target="_blank"><i class="fab fa-discord mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Reddit))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Reddit" class="text-white" target="_blank"><i class="fab fa-reddit-alien mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.BitcoinTalk))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.BitcoinTalk" class="text-white" target="_blank"><i class="fab fa-bitcoin mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.Medium))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.Medium" class="text-white" target="_blank"><i class="fab fa-medium-m mr-2"></i></a>
                    }
                    @if (string.IsNullOrEmpty(@ViewBag.GitHub))
                    {
                        <div class="d-none"></div>
                    }
                    else
                    {
                        <a href="@ViewBag.GitHub" class="text-white" target="_blank"><i class="fab fa-github"></i></a>
                    }
                </div>
            </div>
            <div class="row pb-2 pt-1">
                <div class="col-12 text-center small">
                    Made with <i class="far fa-heart text-danger"></i> by <a href="https://www.solarisplatform.com">Solaris Platform</a>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </footer>
</body>
</html>