Solaris.BlockExplorer.UI/Models/ViewModels/AddressViewModel.cs
using System.Collections.Generic;

namespace Solaris.BlockExplorer.UI.Models.ViewModels
{
    public class AddressViewModel : IAddressViewModel
    {
        public IAddressModel Address { get; set; }
        public PagedResultModel<IEnumerable<AddressTransactionModel>> Transactions { get; set; }
    }
}

Solaris.BlockExplorer.UI/Controllers/AddressController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Solaris.BlockExplorer.UI.Models;
using Solaris.BlockExplorer.UI.Models.ViewModels;
using Solaris.BlockExplorer.UI.Services;

namespace Solaris.BlockExplorer.UI.Controllers
{
    public class AddressController : BaseController
    {
        private readonly IAddressModelService _addressModelService;

        public AddressController(IConfiguration configuration, IAddressModelService addressModelService) : base(configuration)
        {
            _addressModelService = addressModelService;
        }

        [Route("Address/{Id}", Name = "Address")]
        public async Task<IActionResult> Index(string id, PagingModel paging)
        {
            return View(new AddressViewModel
            {
                Address = await _addressModelService.GetAddress(id),
                Transactions = await _addressModelService.GetTransactions(id, paging)
            });
        }
    }
}

Solaris.BlockExplorer.UI/Controllers/QrController.cs
using System.Drawing.Imaging;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using QRCoder;

namespace Solaris.BlockExplorer.UI.Controllers
{
    public class QrController : Controller
    {
        private readonly IMemoryCache _memoryCache;

        public QrController(IMemoryCache memoryCache)
        {
            _memoryCache = memoryCache;
        }

        public IActionResult Index(string id)
        {
            MemoryStream memoryStream;

            if (!_memoryCache.TryGetValue(id, out var qr))
            {
                using (var qrGenerator = new QRCodeGenerator())
                using (var qrCodeData = qrGenerator.CreateQrCode(id, QRCodeGenerator.ECCLevel.Q))
                using (var qrCode = new QRCode(qrCodeData))
                using (var qrCodeAsBitmap = qrCode.GetGraphic(20))
                {
                    memoryStream = new MemoryStream();
                    qrCodeAsBitmap.Save(memoryStream, ImageFormat.Png);

                    _memoryCache.Set(id, memoryStream.ToArray());

                    memoryStream.Position = 0;
                }
            }
            else
            {
                memoryStream = new MemoryStream((byte[])qr);
            }

            return File(memoryStream, "image/png");
        }
    }
}

Solaris.BlockExplorer.UI/Views/Address/Index.cshtml
@{
    ViewData["Title"] = $"{ViewBag.Name} Block Explorer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Globalization
@model Solaris.BlockExplorer.UI.Models.ViewModels.IAddressViewModel
<div class="row mt-2 mb-2 collapse clipboard-success">
    <div class="col-12">
        <div class="alert alert-success" role="alert">
            <span class="align-middle">
                <i class="fas fa-check-circle fa-2x mr-2"></i>
            </span>
            <span class="align-middle">
                The address has been copied to the clipboard
            </span>
        </div>
    </div>
</div>
<div class="row mt-2">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="title-bottom-border mb-2">
                    Details for Address
                </h4>
                <div class="row">
                    <div class="col-8 col-md-10 col-xxl-11">
                        <div class="row rows">
                            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-3 col-xxl-2 col-xxxl-2 text-left row-column text-lightblue">Address</div>
                            <div class="col-sm-9 col-md-10 col-lg-10 col-xl-9 col-xxl-10 col-xxxl-10 text-left row-column">
                                <a href="@Url.Action("Index", new { id = Model.Address.PublicKey })">@Model.Address.PublicKey</a>
                                <i class="ml-2 fas fa-copy cursor-pointer clipboard" title="Copy to clipboard" data-clipboard-text="@Model.Address.PublicKey"></i>
                            </div>
                        </div>
                        <div class="row rows">
                            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-3 col-xxl-2 col-xxxl-2 text-left row-column text-lightblue">Balance</div>
                            <div class="col-sm-9 col-md-10 col-lg-10 col-xl-9 col-xxl-10 col-xxxl-10 text-left row-column">
                                @Model.Address.Balance @ViewBag.Ticker
                            </div>
                        </div>
                        <div class="row rows">
                            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-3 col-xxl-2 col-xxxl-2 text-left row-column text-lightblue">Received</div>
                            <div class="col-sm-9 col-md-10 col-lg-10 col-xl-9 col-xxl-10 col-xxxl-10 text-left row-column">
                                @Model.Address.Received @ViewBag.Ticker (in @Model.Address.ReceivedCount transactions)
                            </div>
                        </div>
                        <div class="row rows">
                            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-3 col-xxl-2 col-xxxl-2 text-left row-column text-lightblue">Sent</div>
                            <div class="col-sm-9 col-md-10 col-lg-10 col-xl-9 col-xxl-10 col-xxxl-10 text-left row-column">
                                @Model.Address.Sent @ViewBag.Ticker (in @Model.Address.SentCount transactions)
                            </div>
                        </div>
                        <div class="row rows">
                            <div class="col-sm-3 col-md-2 col-lg-2 col-xl-3 col-xxl-2 col-xxxl-2 text-left row-column text-lightblue">Staked/Mined</div>
                            <div class="col-sm-9 col-md-10 col-lg-10 col-xl-9 col-xxl-10 col-xxxl-10 text-left row-column">
                                @Model.Address.Mined @ViewBag.Ticker (in @Model.Address.MinedCount transactions)
                            </div>
                        </div>
                    </div>
                    <div class="col-4 col-md-2 col-xxl-1 text-right">
                        <img src="@Url.Action("Index", "Qr", new { Id = Model.Address.PublicKey })" alt="@Model.Address.PublicKey" height="128" class="img-fluid" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mt-2">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="title-bottom-border mb-2">
                    Transactions
                </h4>
                <div class="row row-header">
                    <div class="row-header-column col-5 col-sm-3 col-md-3 text-left">Transaction hash</div>
                    <div class="row-header-column d-none d-lg-block col-md-1 text-right">Block height</div>
                    <div class="row-header-column d-sm-block d-lg-none col-2 col-md-1 text-right">Block#</div>
                    <div class="row-header-column d-none d-md-block col-md-3 text-right">Date</div>
                    <div class="row-header-column col-5 col-sm-3 col-md-2 text-right">Amount</div>
                    <div class="row-header-column d-none d-sm-block col-sm-4 col-md-3 text-right">Balance</div>
                </div>
                <div class="row">
                    <div class="col-12">
                        @foreach (var transaction in Model.Transactions.Result)
                        {
                            <div class="row rows">
                                <div class="row-column col-5 col-sm-3 col-md-3 text-left">
                                    <a href="@Url.Action("Index", "Transaction", new {id = transaction.Id})">@transaction.Id</a>
                                </div>
                                <div class="row-column d-sm-block col-2 col-md-1 text-right">
                                    <a href="@Url.Action("Index", "Block", new {id = transaction.BlockId})">@transaction.BlockHeight</a>
                                </div>
                                <div class="row-column d-none d-md-block col-md-3 text-right">
                                    @DateTimeOffset.FromUnixTimeSeconds(transaction.Time).DateTime.ToString(CultureInfo.CurrentUICulture)
                                </div>
                                <div class="row-column col-5 col-sm-3 col-md-2 text-right">
                                    @if (transaction.IsMined)
                                    {
                                        <span class="d-none d-xl-inline-block badge badge-primary">Reward</span>
                                    }
                                    @transaction.Amount @ViewBag.Ticker
                                </div>
                                <div class="row-column d-none d-sm-block col-sm-4 col-md-3 text-right">
                                    @transaction.Balance @ViewBag.Ticker
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <div class="float-right">
                    <select onchange="setPageSize(this);" class="form-control mt-3 ml-2" style="width: 80px;" id="pageSizeControl">
                        <option value="10">
                            10
                        </option>
                        <option value="25">
                            25
                        </option>
                        <option value="100">
                            100
                        </option>
                        <option value="250">
                            250
                        </option>
                        <option value="500">
                            500
                        </option>
                        <option value="1000">
                            1000
                        </option>
                    </select>
                </div>
                <div class="row mt-2 mb-2">
                    <div class="col-12">
                        <div class="col-11 offset-1 d-flex justify-content-center">
                            <ul class="pagination mt-3 mb-0">
                                @if (Model.Transactions.CurrentPage > 1)
                                {
                                    <li class="page-item"><a class="page-link" href="#" onclick="return setPage(1);"><i class="fas fa-step-backward"></i></a></li>
                                    <li class="page-item"><a class="page-link" href="#" onclick="return setPage(@(Model.Transactions.CurrentPage - 1));"><i class="fas fa-chevron-circle-left mr-2"></i> Previous</a></li>
                                }
                                @for (var i = Model.Transactions.PagingStart; i <= Model.Transactions.PagingEnd; i++)
                                {
                                    <li class="page-item d-none d-md-block @(Model.Transactions.CurrentPage == i ? "active" : "")"><a class="page-link" href="#" onclick="return setPage(@i);">@i</a></li>
                                }
                                @if (Model.Transactions.CurrentPage < Model.Transactions.PageCount)
                                {
                                    <li class="page-item"><a class="page-link" href="#" onclick="return setPage(@(Model.Transactions.CurrentPage + 1));">Next <i class="fas fa-chevron-circle-right ml-2"></i></a></li>
                                    <li class="page-item"><a class="page-link" href="#" onclick="return setPage(@Model.Transactions.PageCount);"><i class="fas fa-step-forward"></i></a></li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="pagingForm" method="get">
    <input type="hidden" name="pageNumber" id="pageNumber" value="@Model.Transactions.CurrentPage" />
    <input type="hidden" name="pageSize" id="pageSize" value="@Model.Transactions.PageSize" />
</form>
<script src="~/js/paging.min.js" asp-append-version="true"></script>